export const NOT_FOUND_USER = "В системі не знайдено користувача за наступними даними";
export const SERVER_ERROR = 'Виникла помилка, спробуйте пізніше';
export const NOT_AUTHORIZED= 'Необхідно авторизуватись';
export const NOT_FOUND_USERS = 'В системі немає користувачів';
export const NOT_FOUND_FACULTIES = "В системі відсутні факультети";
export const NOT_FOUND_GROUPS = "В системі відсутні групи";
export const NOT_FOUND_FACULTY_STUDENTS = 'В системі відсутні студенти на ваших факультетах'
export const NOT_FOUND_LOCAL_ADMINS =  "В системі відсутні керуючі";
export const FIELDS_REQUEST = 'Необхідно заповнити усі поля';
export const LOCAL_ADMIN_ALREADY_EXISTS = 'В системі вже існує обраний керуючий';
export const TEACHER_NOT_EXISTS = 'В системі не знайдено обраного викладача';
export const NOT_FOUND_UNIVERSITIES = 'В системі відсутні університети';
export const STUDENT_ALREADY_EXISTS = 'В системі вже існує обраний студент';
export const NOT_FOUND_FACULTY_TEACHERS = 'В системі відсутні вчителі на ваших факультетах';
export const NOT_FOUND_UNIVERSITY_TEACHERS = 'В системі відсутні вчителі у вашому університеті';
export const TEACHER_ALREADY_EXISTS = 'В системі вже існує обраний вчитель';
export const TEACHER_REVIEWS_NOT_EXISTS = 'В системі поки що немає відгуків на обраного викладача'
export const ACTIVE_REVIEW_NOT_FOUND =  "Для вас немає активних опитувань на обраного викладача";
export const LEAVE_REVIEW_NOT_ALLOW = "Тільки студенти університу можуть залишати відгуки на вчителів";
export const LEAVED_REVIEW_ALREADY_EXIST = ACTIVE_REVIEW_NOT_FOUND;